### ISSUE TITLE
Support "cargo release"

### ISSUE THREAD

**Issue by orf** [actions-rs/cargo#10]
[cargo-release](https://github.com/sunng87/cargo-release) is pretty awesome, and it seems github actions would be perfect to build releases across multiple operating systems.

Can we bake `cargo-release` into this workflow, or provide a way to use it?

**Comment by svartalf** [comment]
Hey, @orf, release activities are discussed at the #6, let's group the collective ideas in a one place.

I'm going to close this one issue, but I would love to hear what are thinking about [these questions](https://github.com/actions-rs/meta/issues/6#issuecomment-534134424) specifically.
