### ISSUE TITLE
Cargo builds on macOS runners have ephemeral failures

### ISSUE THREAD

**Issue by echeran** [actions-rs/cargo#111]
I have a question about running Cargo builds on macOS, and I was wondering if someone might know the answer.

We've been experience flaky builds (https://github.com/unicode-org/icu4x/issues/201) caused by ephemeral build errors that appear to have started showing up all of a sudden on a few PRs.

The error message in the log mentions `error[E0463]: can't find crate for serde_derive which serde depends on`, and when I looked through https://github.com/serde-rs/serde/issues/856 and similar issues (and verified the transitive dependencies' versions of serde used, using [`cargo-tree`](https://github.com/sfackler/cargo-tree)), I don't see the same serde version conflict problems that were described.  And either way, I don't think that would explain the ephemeral nature.

One possible theory is that it might relate to this issue from 3 years ago of cargo build failing on macOS due to linking issues when dependencies are added (https://github.com/rust-lang/cargo/issues/4775).  I don't know if that is still relevant to cargo builds.  The GH builds that use the GH caching action (thereby retrieving cargo crate cache) are the ones that seem to fail ephemerally ([ex1](https://github.com/unicode-org/icu4x/pull/209/checks?check_run_id=1013449918), [ex2](https://github.com/unicode-org/icu4x/pull/209/checks?check_run_id=1010376220)).  The tests run after I turned off the GH caching action seem to pass ([ex1](https://github.com/unicode-org/icu4x/runs/1003965005?check_suite_focus=true), [ex2](https://github.com/unicode-org/icu4x/runs/1013421177?check_suite_focus=true)).  And FWIW, in my personal fork, even when I leave the GH cache action on, the builds pass ([ex1](https://github.com/echeran/icu4x/pull/7/checks?check_run_id=1013421140), [ex2](https://github.com/echeran/icu4x/pull/8/checks?check_run_id=1013450063)).

Any pointers or suggestions would be appreciated, thanks.

**Comment by piscisaureus** [comment]
I'm experiencing the same issue, also on macOS.
(https://github.com/denoland/rusty_v8/runs/1037356000?check_suite_focus=true).

**Comment by ohsayan** [comment]
I'm having the same problem here: https://github.com/terrabasedb/terrabase/runs/1055128389#step:7:86

**Comment by link2xt** [comment]
Same, on https://github.com/deltachat/deltachat-core-rust/ it randomly fails with
```
error[E0463]: can't find crate for `num_derive`
```

**Comment by svartalf** [comment]
Common conclusion is that it is related to caching (also helped me with the same problem).
Since this issue is not related to this Action, I'm going to close it.

**Comment by lilith** [comment]
I think we're encountering this too with https://github.com/imazen/imageflow 

We have a large build and caching is really important. Has anyone figured out how to fix it?

**Comment by lilith** [comment]
It sounds like this is related to needing GNU tar instead of BSD tar on OS X- https://github.com/actions/cache/issues/403
