### ISSUE TITLE
ENOENT on macos-latest with cross

### ISSUE THREAD

**Issue by matchai** [actions-rs/cargo#2]
Great work on `actions-rs` so far! 😄 

Here is an example of the failure: https://github.com/matchai/test-rust-actions/runs/222483203
The same run contains a Linux build that runs successfully.

**Comment by svartalf** [comment]
Hm, yes, `rust` and `cargo` are not installed by default in the [macOS environments](https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions), so you need to use the [`actions-rs/toolchain`](https://github.com/actions-rs/toolchain) to install it manually:

```yml
- uses: actions-rs/toolchain@master
  with:
    toolchain: stable
    override: true
```

Error message is quite cryptic though, 0deeed314be64c417a205daec6cb7edd5cc0ab62 should handle that now and show this message in the logs:

```
cargo is not installed by default for some virtual environments, see https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions
To install it, use this action: https://github.com/actions-rs/toolchain
##[error]Unable to locate executable file: cargo. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
##[error]Node run failed with exit code 1
```
Can you restart your workflow to check it?

**Comment by matchai** [comment]
The error message makes it _much_ clearer!
Thank you for the quick update. 😄 

https://github.com/matchai/test-rust-actions/runs/222912419

**Comment by svartalf** [comment]
Great! Thanks for an issue :)

Btw, I published the `v1` tag recently in order to make the release process more organized, I would like to suggest you to switch all `actions-rs/*` actions from the `@master` tag to the `@v1`; hopefully `@v1` actions will be backward-compatible all the time :)
