### ISSUE TITLE
How to save output of cargo command?

### ISSUE THREAD

**Issue by jadamcrain** [actions-rs/cargo#214]
How do I save the output of a cargo command to file in a Github action?

Specifically, I want to do something like:

`cargo build --message-format json > build.log` to save a log of the build in my CI.

**Comment by eggbean** [comment]
Doesn't the `tee` command work?

    cargo build --message-format json | tee build.log

**Comment by jadamcrain** [comment]
It's funny I don't even remember opening ticket. 

We just used ended up using the cargo invocation within this action doing:

Windows:

```
cargo --message-format json | Out-File -encoding "UTF8" .\build.log
```

Changing the default powershell encoding was important so that serde based JSON parser could read it back in.

Linux:

```
cargo build -message-format json > ./build.log
```
