### ISSUE TITLE
Fails on bytes crate

### ISSUE THREAD

**Issue by tekjar** [actions-rs/cargo#33]
```
error: `core::slice::<impl [T]>::len` is not yet stable as a const fn
##[error]   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.2/src/bytes.rs:121:18
```
Is 1.39 supported or is this an unreleated error?

**Comment by svartalf** [comment]
Hey, @tekjar!

This action is using whatever Rust is available (which is by default is whatever Rust version [installed on the VMs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners)), you can use [`actions-rs/toolchain`](https://github.com/actions-rs/toolchain) Action to install specific Rust version that you need.
