### ISSUE TITLE
miri seems to hang

### ISSUE THREAD

**Issue by Ralith** [actions-rs/cargo#34]
For example, see https://github.com/Ralith/hecs/pull/4; as of this writing various attempts at this have spun for upwards of twenty minutes before being cancelled, while a local run completes in seconds. Not sure how to get any feedback from the action while it's running, so it's unclear what might be happening here.

**Comment by Ralith** [comment]
Finally timed out after six hours:
```
 /usr/share/rust/.cargo/bin/cargo miri test --all-features
I will run `"/usr/share/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo" "/usr/share/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo" "install" "xargo" "-f"` to install a recent enough xargo. Proceed? [Y/n] 
##[error]The operation was canceled.
```

**Comment by Ralith** [comment]
Adding a step to run `cargo install miri` seems to do the trick. Takes a while to build, though; would be cool to have caching!

**Comment by svartalf** [comment]
I guess, it hungs awaiting for the user input?

For clarity, I'm going to link the related issue in case anyone would want to do the same: https://github.com/actions-rs/meta/issues/24

**Comment by Ralith** [comment]
Yeah, pretty easy fix in the end.
