### ISSUE TITLE
Cargo login issues

### ISSUE THREAD

**Issue by zbrox** [actions-rs/cargo#4]
When trying to use `cargo login` in preparation of publishing to crates.io the token is not passed a cargo login argument and then the command hangs indefinitely waiting for input.

Example task:

```yaml
- name: Login to crates.io
  uses: actions-rs/cargo@v1
  with:
    toolchain: nightly
    command: login
    arguments: ${{ secrets.CRATES_TOKEN }}
```

I'm new to GitHub actions so I'm not sure if maybe I'm misusing this and I need to pass the argument in another way.

**Comment by svartalf** [comment]
Oh, I'm sorry, there is a typo in the README example, could you replace `arguments` input with the `args` and try again?

```
- name: Login to crates.io
  uses: actions-rs/cargo@v1
  with:
    toolchain: nightly
    command: login
    args: ${{ secrets.CRATES_TOKEN }}
```

**Comment by svartalf** [comment]
Fixed typo in the 2c42f22fe4080ef98db93b9cbec4f18c722e0890

**Comment by svartalf** [comment]
Also, I tested a login command with the following workflow, works great:

```yaml
on: [push]

name: Test login

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_TOKEN }}
```


```
##[debug]Evaluating condition for step: 'Run actions-rs/cargo@v1'
##[debug]Parsing expression: <success()>
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run actions-rs/cargo@v1
##[debug]Loading inputs
##[debug]Evaluating: secrets.CRATES_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'CRATES_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run actions-rs/cargo@v1
/usr/share/rust/.cargo/bin/cargo login ***
       Login token for `crates.io` saved
##[debug]Finishing: Run actions-rs/cargo@v1
```

**Comment by zbrox** [comment]
Thanks! Will replace it in my workflows now.

**Comment by zbrox** [comment]
Thanks again for the quick help!  The login action already passed successfully. This would also explain why I had problems packaging the product of `cargo build --release` because the `--release` flag was probably not being passed and I was looking in the wrong folder :)

**Comment by svartalf** [comment]
@zbrox great! You can also join the [gitter chat](https://gitter.im/actions-rs/community) if you have any questions left or need a help

**Comment by iamgabrielsoft** [comment]
mine get stuck, without any github actions
