### ISSUE TITLE
Cross build fails when trying to parse manifest at Cargo.toml

### ISSUE THREAD

**Issue by fxwiegand** [actions-rs/cargo#87]
## Description

I am trying to build my project for `arm-unknown-linux-gnueabihf` using a slight modified version of the cross example that's provided in the README.md. The Build fails when trying to parse a manifest in the Cargo.toml.

## Workflow code

[This](https://github.com/fxwiegand/rustberry-weather/actions/runs/133233957/workflow) is the workflow file.
 
## Action output

Log from my [run](https://github.com/fxwiegand/rustberry-weather/runs/765160142?check_suite_focus=true):

```
Downloaded hyper v0.10.16
error: failed to parse manifest at `/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/Cargo.toml`
##[error]failed to parse manifest at `/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/Cargo.toml`
Caused by:
readme file with name 'README.md' was not found
##[error]The process 'cross' failed with exit code 101
```

In [another run](https://github.com/fxwiegand/rustberry-weather/runs/765383635) the same error occurs with a different crate: ```##[error]failed to parse manifest at /cargo/registry/src/github.com-1ecc6299db9ec823/time-macros-impl-0.1.1/Cargo.toml```

## Expected behavior

I tried building my project locally with cross for the same target without this happening.

**Comment by svartalf** [comment]
This is unrelated both to `actions-rs` and `cross`, see https://github.com/rust-lang/cargo/issues/8354
